// 200 test students across grades K-5. Generated fixture data.
export const UNITS = [
  {
    "name": "ER / Light Blue",
    "color": "#29B6F6"
  },
  {
    "name": "ER / Green",
    "color": "#43A047"
  },
  {
    "name": "ER / Orange",
    "color": "#FB8C00"
  },
  {
    "name": "ER / Purple",
    "color": "#7E57C2"
  },
  {
    "name": "ER / Red",
    "color": "#E53935"
  }
]

export const students = [
  { id: '4433983', lastName: 'Adams', firstName: 'Aaron', grade: '5', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433899', lastName: 'Adams', firstName: 'Amelia', grade: '2', unit: null, assignedGroups: [] },
  { id: '4434112', lastName: 'Adams', firstName: 'Charles', grade: '5', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4434031', lastName: 'Adams', firstName: 'David', grade: '2', unit: null, assignedGroups: ['Willow Leaves', 'Birch Leaves'] },
  { id: '4434157', lastName: 'Adams', firstName: 'Emma', grade: '3', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4434028', lastName: 'Adams', firstName: 'Joseph', grade: '1', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434190', lastName: 'Anderson', firstName: 'Alexander', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434037', lastName: 'Anderson', firstName: 'Chloe', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434058', lastName: 'Anderson', firstName: 'Elena', grade: '5', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433740', lastName: 'Anderson', firstName: 'Nolan', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Aspen Leaves'] },
  { id: '4434067', lastName: 'Anderson', firstName: 'Scarlett', grade: 'K', unit: null, assignedGroups: ['Birch Leaves'] },
  { id: '4433803', lastName: 'Anderson', firstName: 'Victoria', grade: 'K', unit: null, assignedGroups: ['Aspen Leaves', 'Birch Leaves'] },
  { id: '4434139', lastName: 'Beaumont', firstName: 'Hazel', grade: '1', unit: null, assignedGroups: [] },
  { id: '4433908', lastName: 'Beaumont', firstName: 'Lucas', grade: '4', unit: null, assignedGroups: ['Maple Leaves'] },
  { id: '4433812', lastName: 'Beaumont', firstName: 'Sophia', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433773', lastName: 'Bennett', firstName: 'Adrian', grade: '5', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433926', lastName: 'Bennett', firstName: 'Carter', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Birch Leaves'] },
  { id: '4434262', lastName: 'Bennett', firstName: 'Scarlett', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434265', lastName: 'Brown', firstName: 'Dylan', grade: '1', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433827', lastName: 'Brown', firstName: 'Isaac', grade: '2', unit: null, assignedGroups: ['Birch Leaves', 'Maple Leaves'] },
  { id: '4434133', lastName: 'Brown', firstName: 'John', grade: '3', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4434070', lastName: 'Brown', firstName: 'Thomas', grade: '3', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Birch Leaves', 'Willow Leaves'] },
  { id: '4434229', lastName: 'Carter', firstName: 'Levi', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433791', lastName: 'Carter', firstName: 'Thomas', grade: '2', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433971', lastName: 'Castillo', firstName: 'Allison', grade: '1', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Maple Leaves'] },
  { id: '4434289', lastName: 'Castillo', firstName: 'Ava', grade: '5', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434106', lastName: 'Castillo', firstName: 'Charles', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4433956', lastName: 'Clark', firstName: 'Alexander', grade: '4', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433755', lastName: 'Clark', firstName: 'John', grade: '2', unit: null, assignedGroups: [] },
  { id: '4434043', lastName: 'Clark', firstName: 'Julian', grade: '5', unit: null, assignedGroups: ['Aspen Leaves'] },
  { id: '4434082', lastName: 'Clark', firstName: 'Levi', grade: 'K', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Aspen Leaves'] },
  { id: '4434004', lastName: 'Clark', firstName: 'Lincoln', grade: '3', unit: null, assignedGroups: [] },
  { id: '4434136', lastName: 'Clark', firstName: 'Luke', grade: '4', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4433941', lastName: 'Davis', firstName: 'Alexa', grade: '3', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434247', lastName: 'Davis', firstName: 'Mason', grade: '2', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Oak Leaves', 'Willow Leaves'] },
  { id: '4433770', lastName: 'Diaz', firstName: 'Colton', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4433719', lastName: 'Diaz', firstName: 'Matthew', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433962', lastName: 'Evans', firstName: 'Amara', grade: '2', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Willow Leaves'] },
  { id: '4434091', lastName: 'Evans', firstName: 'Amelia', grade: '1', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433869', lastName: 'Evans', firstName: 'Anthony', grade: '2', unit: null, assignedGroups: ['Maple Leaves', 'Willow Leaves'] },
  { id: '4433851', lastName: 'Evans', firstName: 'Aria', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434304', lastName: 'Evans', firstName: 'Claire', grade: '5', unit: null, assignedGroups: ['Oak Leaves', 'Birch Leaves'] },
  { id: '4434286', lastName: 'Evans', firstName: 'Lucy', grade: 'K', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434232', lastName: 'Evans', firstName: 'Riley', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433944', lastName: 'Evans', firstName: 'Savannah', grade: 'K', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434076', lastName: 'Evans', firstName: 'Scarlett', grade: '1', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4434253', lastName: 'Foster', firstName: 'Colton', grade: '2', unit: null, assignedGroups: ['Willow Leaves', 'Maple Leaves'] },
  { id: '4433920', lastName: 'Foster', firstName: 'Dylan', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4434103', lastName: 'Foster', firstName: 'Grace', grade: '4', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Aspen Leaves', 'Birch Leaves'] },
  { id: '4434280', lastName: 'Gonzalez', firstName: 'Cameron', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4434022', lastName: 'Gonzalez', firstName: 'Diego', grade: '2', unit: null, assignedGroups: [] },
  { id: '4434202', lastName: 'Gonzalez', firstName: 'Luke', grade: '2', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Willow Leaves'] },
  { id: '4433743', lastName: 'Gonzalez', firstName: 'Sarah', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Willow Leaves', 'Oak Leaves'] },
  { id: '4433995', lastName: 'Harris', firstName: 'Claire', grade: '4', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433713', lastName: 'Harris', firstName: 'Olivia', grade: '1', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433950', lastName: 'Harris', firstName: 'Thomas', grade: '5', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433887', lastName: 'Hughes', firstName: 'Jackson', grade: '1', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433911', lastName: 'Hughes', firstName: 'Mason', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Aspen Leaves'] },
  { id: '4434046', lastName: 'Ibrahim', firstName: 'Alexa', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433860', lastName: 'Ibrahim', firstName: 'Alexander', grade: '5', unit: null, assignedGroups: ['Birch Leaves'] },
  { id: '4434274', lastName: 'Ibrahim', firstName: 'Elijah', grade: '2', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434151', lastName: 'Jenkins', firstName: 'Charles', grade: '5', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433866', lastName: 'Jenkins', firstName: 'Hazel', grade: '1', unit: null, assignedGroups: ['Maple Leaves', 'Oak Leaves'] },
  { id: '4434079', lastName: 'Jenkins', firstName: 'Joshua', grade: '5', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433809', lastName: 'Jenkins', firstName: 'Madelyn', grade: '3', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433986', lastName: 'Jenkins', firstName: 'Matthew', grade: '1', unit: null, assignedGroups: [] },
  { id: '4433776', lastName: 'Jenkins', firstName: 'Nora', grade: '3', unit: null, assignedGroups: ['Aspen Leaves', 'Maple Leaves'] },
  { id: '4434118', lastName: 'Johnson', firstName: 'Aaron', grade: '1', unit: null, assignedGroups: [] },
  { id: '4433731', lastName: 'Johnson', firstName: 'Omar', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433749', lastName: 'Kim', firstName: 'Allison', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434244', lastName: 'Kim', firstName: 'Elena', grade: '3', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4434052', lastName: 'Kim', firstName: 'Jackson', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434001', lastName: 'Kim', firstName: 'Zoey', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433932', lastName: 'Lee', firstName: 'Caleb', grade: '5', unit: null, assignedGroups: ['Oak Leaves'] },
  { id: '4434211', lastName: 'Lee', firstName: 'Christopher', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433737', lastName: 'Lee', firstName: 'Colton', grade: '5', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4433992', lastName: 'Lopez', firstName: 'Cameron', grade: 'K', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433953', lastName: 'Lopez', firstName: 'Thomas', grade: 'K', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434097', lastName: 'Martinez', firstName: 'Alexander', grade: '2', unit: null, assignedGroups: ['Birch Leaves', 'Aspen Leaves'] },
  { id: '4433848', lastName: 'Martinez', firstName: 'Caleb', grade: '2', unit: null, assignedGroups: ['Birch Leaves', 'Willow Leaves'] },
  { id: '4433815', lastName: 'Martinez', firstName: 'Daniel', grade: '4', unit: null, assignedGroups: [] },
  { id: '4433929', lastName: 'Martinez', firstName: 'David', grade: '4', unit: null, assignedGroups: ['Aspen Leaves', 'Birch Leaves'] },
  { id: '4433746', lastName: 'Martinez', firstName: 'Ethan', grade: '2', unit: null, assignedGroups: [] },
  { id: '4434214', lastName: 'Martinez', firstName: 'Hazel', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4434013', lastName: 'Martinez', firstName: 'Mia', grade: '3', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434040', lastName: 'Martinez', firstName: 'Victoria', grade: '1', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4433857', lastName: 'Martinez', firstName: 'Wyatt', grade: '3', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434220', lastName: 'Miller', firstName: 'Anthony', grade: '1', unit: null, assignedGroups: [] },
  { id: '4434199', lastName: 'Miller', firstName: 'Emily', grade: '1', unit: null, assignedGroups: ['Aspen Leaves'] },
  { id: '4434307', lastName: 'Miller', firstName: 'Isaac', grade: '5', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434154', lastName: 'Moore', firstName: 'Audrey', grade: '4', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434241', lastName: 'Moore', firstName: 'Benjamin', grade: '1', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433884', lastName: 'Moore', firstName: 'Daniel', grade: '3', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433980', lastName: 'Moore', firstName: 'Elena', grade: '4', unit: null, assignedGroups: ['Willow Leaves', 'Aspen Leaves'] },
  { id: '4433833', lastName: 'Moore', firstName: 'Genesis', grade: 'K', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433959', lastName: 'Moore', firstName: 'Nathan', grade: '1', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Birch Leaves'] },
  { id: '4433806', lastName: 'Moore', firstName: 'Sophia', grade: '2', unit: null, assignedGroups: ['Aspen Leaves'] },
  { id: '4434193', lastName: 'Moore', firstName: 'Thomas', grade: '1', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Aspen Leaves'] },
  { id: '4433893', lastName: 'Murphy', firstName: 'Allison', grade: '2', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433794', lastName: 'Murphy', firstName: 'Henry', grade: '1', unit: null, assignedGroups: [] },
  { id: '4433872', lastName: 'Murphy', firstName: 'Kennedy', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434271', lastName: 'Murphy', firstName: 'Mateo', grade: 'K', unit: null, assignedGroups: ['Maple Leaves'] },
  { id: '4434238', lastName: 'Nelson', firstName: 'Alexa', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433968', lastName: 'Nelson', firstName: 'Ariana', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434010', lastName: 'Nelson', firstName: 'Eli', grade: '3', unit: null, assignedGroups: ['Oak Leaves'] },
  { id: '4434250', lastName: 'Nelson', firstName: 'John', grade: '3', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Oak Leaves', 'Aspen Leaves'] },
  { id: '4433863', lastName: 'Nelson', firstName: 'Ryan', grade: '4', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433722', lastName: 'Nelson', firstName: 'Wyatt', grade: '4', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Aspen Leaves', 'Oak Leaves'] },
  { id: '4434226', lastName: 'Nguyen', firstName: 'Thomas', grade: '1', unit: null, assignedGroups: ['Willow Leaves', 'Maple Leaves'] },
  { id: '4433821', lastName: 'Ortiz', firstName: 'Cameron', grade: '3', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Maple Leaves', 'Oak Leaves'] },
  { id: '4434268', lastName: 'Ortiz', firstName: 'Claire', grade: '4', unit: null, assignedGroups: [] },
  { id: '4433836', lastName: 'Ortiz', firstName: 'Daniel', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434196', lastName: 'Ortiz', firstName: 'Madelyn', grade: '4', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4434235', lastName: 'Owens', firstName: 'Diego', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Birch Leaves', 'Maple Leaves'] },
  { id: '4434007', lastName: 'Owens', firstName: 'Genesis', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433728', lastName: 'Owens', firstName: 'Joseph', grade: '5', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Oak Leaves'] },
  { id: '4434184', lastName: 'Owens', firstName: 'Lincoln', grade: '2', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4433977', lastName: 'Owens', firstName: 'Nolan', grade: 'K', unit: null, assignedGroups: ['Maple Leaves', 'Birch Leaves'] },
  { id: '4434019', lastName: 'Owens', firstName: 'Owen', grade: '4', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4434034', lastName: 'Owens', firstName: 'Valentina', grade: '4', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433779', lastName: 'Parker', firstName: 'Christopher', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4434172', lastName: 'Parker', firstName: 'Daniel', grade: '4', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434145', lastName: 'Parker', firstName: 'Omar', grade: '4', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4434016', lastName: 'Patel', firstName: 'Ariana', grade: '1', unit: null, assignedGroups: ['Maple Leaves', 'Willow Leaves'] },
  { id: '4433710', lastName: 'Patel', firstName: 'Jackson', grade: '2', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433905', lastName: 'Patel', firstName: 'Layla', grade: '2', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Willow Leaves'] },
  { id: '4433890', lastName: 'Patel', firstName: 'Levi', grade: '5', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434088', lastName: 'Quinn', firstName: 'Amara', grade: '4', unit: null, assignedGroups: [] },
  { id: '4434223', lastName: 'Quinn', firstName: 'Chloe', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433974', lastName: 'Quinn', firstName: 'Christopher', grade: '4', unit: null, assignedGroups: [] },
  { id: '4433914', lastName: 'Quinn', firstName: 'Riley', grade: '3', unit: null, assignedGroups: ['Aspen Leaves', 'Willow Leaves'] },
  { id: '4433947', lastName: 'Reed', firstName: 'Carter', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433767', lastName: 'Reed', firstName: 'Christian', grade: 'K', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433935', lastName: 'Reed', firstName: 'Elijah', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Maple Leaves'] },
  { id: '4434298', lastName: 'Reed', firstName: 'Kennedy', grade: '5', unit: null, assignedGroups: ['Oak Leaves', 'Willow Leaves'] },
  { id: '4434205', lastName: 'Reed', firstName: 'Noah', grade: '3', unit: null, assignedGroups: [] },
  { id: '4434094', lastName: 'Rodriguez', firstName: 'Anna', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4434127', lastName: 'Rodriguez', firstName: 'Caleb', grade: '4', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433854', lastName: 'Rodriguez', firstName: 'Genesis', grade: '3', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434142', lastName: 'Rodriguez', firstName: 'Isabella', grade: '5', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433824', lastName: 'Rodriguez', firstName: 'Maya', grade: 'K', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Maple Leaves'] },
  { id: '4434073', lastName: 'Rodriguez', firstName: 'Naomi', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4433923', lastName: 'Rodriguez', firstName: 'Savannah', grade: '4', unit: null, assignedGroups: [] },
  { id: '4434283', lastName: 'Sanders', firstName: 'Cameron', grade: '1', unit: null, assignedGroups: [] },
  { id: '4434292', lastName: 'Sanders', firstName: 'Sophia', grade: '5', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Birch Leaves'] },
  { id: '4433758', lastName: 'Smith', firstName: 'Victoria', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433725', lastName: 'Taylor', firstName: 'Eli', grade: '4', unit: null, assignedGroups: [] },
  { id: '4434187', lastName: 'Taylor', firstName: 'Genesis', grade: '4', unit: null, assignedGroups: [] },
  { id: '4433938', lastName: 'Taylor', firstName: 'Mason', grade: '2', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434124', lastName: 'Torres', firstName: 'Ethan', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433830', lastName: 'Torres', firstName: 'Joshua', grade: '5', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Oak Leaves', 'Maple Leaves'] },
  { id: '4433878', lastName: 'Upton', firstName: 'Amara', grade: 'K', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434109', lastName: 'Upton', firstName: 'Andrew', grade: '1', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Willow Leaves'] },
  { id: '4434178', lastName: 'Upton', firstName: 'Ava', grade: '3', unit: null, assignedGroups: ['Birch Leaves', 'Maple Leaves'] },
  { id: '4433845', lastName: 'Upton', firstName: 'Brooklyn', grade: '2', unit: null, assignedGroups: [] },
  { id: '4434175', lastName: 'Upton', firstName: 'Cameron', grade: '2', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Willow Leaves'] },
  { id: '4434256', lastName: 'Upton', firstName: 'Carter', grade: '1', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433800', lastName: 'Upton', firstName: 'Joseph', grade: '2', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: [] },
  { id: '4434259', lastName: 'Upton', firstName: 'Kennedy', grade: '5', unit: null, assignedGroups: [] },
  { id: '4433761', lastName: 'Upton', firstName: 'Layla', grade: '5', unit: null, assignedGroups: ['Oak Leaves'] },
  { id: '4434025', lastName: 'Upton', firstName: 'Sarah', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433788', lastName: 'Vargas', firstName: 'Brooklyn', grade: '1', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Birch Leaves'] },
  { id: '4434217', lastName: 'Vargas', firstName: 'Isabella', grade: '4', unit: null, assignedGroups: ['Birch Leaves'] },
  { id: '4433839', lastName: 'Vargas', firstName: 'Lucas', grade: '5', unit: null, assignedGroups: [] },
  { id: '4434301', lastName: 'Vargas', firstName: 'Omar', grade: '1', unit: null, assignedGroups: ['Birch Leaves'] },
  { id: '4433785', lastName: 'Vargas', firstName: 'Victoria', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4434130', lastName: 'Vaughn', firstName: 'Daniel', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4434166', lastName: 'Vaughn', firstName: 'Joshua', grade: '2', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434115', lastName: 'Vaughn', firstName: 'Maya', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4433965', lastName: 'Vaughn', firstName: 'Sophia', grade: '4', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4433734', lastName: 'Walker', firstName: 'Amelia', grade: '1', unit: null, assignedGroups: ['Maple Leaves'] },
  { id: '4434100', lastName: 'Walker', firstName: 'Elena', grade: '4', unit: null, assignedGroups: ['Willow Leaves', 'Birch Leaves'] },
  { id: '4434121', lastName: 'Wallace', firstName: 'Elijah', grade: '5', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433752', lastName: 'Williams', firstName: 'Aaliyah', grade: '1', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434169', lastName: 'Williams', firstName: 'Amelia', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Maple Leaves'] },
  { id: '4433782', lastName: 'Williams', firstName: 'Diego', grade: 'K', unit: null, assignedGroups: ['Willow Leaves'] },
  { id: '4433917', lastName: 'Williams', firstName: 'Everly', grade: '4', unit: null, assignedGroups: [] },
  { id: '4434148', lastName: 'Williams', firstName: 'Jack', grade: 'K', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Oak Leaves'] },
  { id: '4434085', lastName: 'Williams', firstName: 'Layla', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433902', lastName: 'Xiong', firstName: 'Adeline', grade: '3', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4433716', lastName: 'Xiong', firstName: 'Caleb', grade: '1', unit: null, assignedGroups: ['Birch Leaves'] },
  { id: '4434055', lastName: 'Xiong', firstName: 'James', grade: '1', unit: null, assignedGroups: ['Aspen Leaves'] },
  { id: '4434049', lastName: 'Xiong', firstName: 'Madelyn', grade: '3', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: ['Willow Leaves'] },
  { id: '4433881', lastName: 'Xiong', firstName: 'Naomi', grade: '3', unit: null, assignedGroups: [] },
  { id: '4433896', lastName: 'Yates', firstName: 'Andrew', grade: '3', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4434277', lastName: 'Yates', firstName: 'Joshua', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: ['Willow Leaves'] },
  { id: '4434208', lastName: 'Young', firstName: 'Isabella', grade: '2', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: ['Birch Leaves'] },
  { id: '4434061', lastName: 'Young', firstName: 'Scarlett', grade: '1', unit: { name: 'ER / Purple', color: '#7E57C2' }, assignedGroups: ['Oak Leaves'] },
  { id: '4433764', lastName: 'Young', firstName: 'Skylar', grade: '5', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4433842', lastName: 'Zhang', firstName: 'Bella', grade: '5', unit: { name: 'ER / Light Blue', color: '#29B6F6' }, assignedGroups: [] },
  { id: '4433998', lastName: 'Zhang', firstName: 'Colton', grade: 'K', unit: null, assignedGroups: [] },
  { id: '4434295', lastName: 'Zhang', firstName: 'Isaac', grade: '2', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: [] },
  { id: '4434163', lastName: 'Zhang', firstName: 'Joshua', grade: '1', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433818', lastName: 'Zhang', firstName: 'Valentina', grade: '3', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Oak Leaves', 'Willow Leaves'] },
  { id: '4434181', lastName: 'Zhang', firstName: 'Wyatt', grade: '4', unit: null, assignedGroups: ['Oak Leaves'] },
  { id: '4433797', lastName: 'Zimmerman', firstName: 'Aria', grade: 'K', unit: { name: 'ER / Orange', color: '#FB8C00' }, assignedGroups: [] },
  { id: '4434160', lastName: 'Zimmerman', firstName: 'Daniel', grade: '2', unit: { name: 'ER / Green', color: '#43A047' }, assignedGroups: [] },
  { id: '4433875', lastName: 'Zimmerman', firstName: 'Madelyn', grade: 'K', unit: null, assignedGroups: ['Maple Leaves'] },
  { id: '4434064', lastName: 'Zimmerman', firstName: 'Mateo', grade: 'K', unit: { name: 'ER / Red', color: '#E53935' }, assignedGroups: ['Oak Leaves'] },
  { id: '4433989', lastName: 'Zimmerman', firstName: 'Penelope', grade: '5', unit: null, assignedGroups: [] },
]
